﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MyTy.Blog.Web.Models.GitHub;
using Refit;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
    }
}

namespace MyTy.Blog.Web.Models.Github
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIGitHubApi : IGitHubApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIGitHubApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<ContentResult[]> GetContent(string owner,string repo,string path,string token)
        {
            var arguments = new object[] { owner,repo,path,token };
            return (Task<ContentResult[]>) methodImpls["GetContent"](Client, arguments);
        }

        public virtual Task<TreeResult> GetTree(string owner,string repo,string sha,string token)
        {
            var arguments = new object[] { owner,repo,sha,token };
            return (Task<TreeResult>) methodImpls["GetTree"](Client, arguments);
        }

        public virtual Task<TreeResult> GetTreeRecursively(string owner,string repo,string sha,string token)
        {
            var arguments = new object[] { owner,repo,sha,token };
            return (Task<TreeResult>) methodImpls["GetTreeRecursively"](Client, arguments);
        }

        public virtual Task<Blob> GetBlob(string owner,string repo,string sha,string token)
        {
            var arguments = new object[] { owner,repo,sha,token };
            return (Task<Blob>) methodImpls["GetBlob"](Client, arguments);
        }

    }
}


